# Generated by Django 4.2.7 on 2023-11-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
