# Generated by Django 4.2.7 on 2023-11-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_recurringexpense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringexpense',
            old_name='next_due_date',
            new_name='recurring_from',
        ),
    ]
