# Generated by Django 4.2.7 on 2023-12-10 17:03

from django.db import migrations, models
import django.db.models.deletion
import expenses.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_remove_expense_category_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=expenses.models.default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='expenses.category'),
        ),
    ]
